DROP TABLE IF EXISTS EQUIPO;
CREATE TABLE IF NOT EXISTS EQUIPO (
	ID_EQUIPO INT AUTO_INCREMENT,
    NOMBRE VARCHAR(30) NOT NULL,
    APODO VARCHAR (20),
    ID_CIUDAD INT NOT NULL,
    ID_ESTADIO INT NOT NULL,
    ID_ENTRENADOR INT NOT NULL,
    INDEX (ID_EQUIPO, ID_CIUDAD, ID_ENTRENADOR, ID_ESTADIO),
    PRIMARY KEY (ID_EQUIPO)
); 	

DROP TABLE IF EXISTS CIUDAD;
CREATE TABLE IF NOT EXISTS CIUDAD (
	ID_CIUDAD INT AUTO_INCREMENT,
    NOMBRE VARCHAR(30) UNIQUE,
    INDEX (ID_CIUDAD),
    PRIMARY KEY (ID_CIUDAD)
);

DROP TABLE IF EXISTS ENTRENADOR;
CREATE TABLE IF NOT EXISTS ENTRENADOR (
	ID_ENTRENADOR INT AUTO_INCREMENT,
    NOMBRE VARCHAR(30) NOT NULL,
    APELLIDO VARCHAR(30) NOT NULL,
    NACIONALIDAD VARCHAR(20),
    TITULOS_OBTENIDOS INT,
    INDEX (ID_ENTRENADOR, TITULOS_OBTENIDOS),
    PRIMARY KEY (ID_ENTRENADOR)
);

DROP TABLE IF EXISTS PARTIDO;
CREATE TABLE IF NOT EXISTS PARTIDO (
	ID_PARTIDO INT AUTO_INCREMENT,
    FECHA DATETIME,
    ID_EQUIPO_1 INT NOT NULL,
    ID_EQUIPO_2 INT NOT NULL,
    ID_ESTADIO INT NOT NULL,
    INDEX (ID_PARTIDO, ID_EQUIPO_1, ID_EQUIPO_2, ID_ESTADIO),
    PRIMARY KEY (ID_PARTIDO)
);

DROP TABLE IF EXISTS ESTADIO;
CREATE TABLE IF NOT EXISTS ESTADIO (
	ID_ESTADIO INT AUTO_INCREMENT,
    NOMBRE VARCHAR(30) NOT NULL,
    ID_CIUDAD INT NOT NULL,
    INDEX (ID_ESTADIO, ID_CIUDAD),
    PRIMARY KEY (ID_ESTADIO)
);

DROP TABLE IF EXISTS EQUIPO_JUGADOR;
CREATE TABLE IF NOT EXISTS EQUIPO_JUGADOR (
	ID_EQUIPO_JUGADOR INT AUTO_INCREMENT,
    NUMERO INT NOT NULL,
    ID_EQUIPO INT NOT NULL,
    ID_JUGADOR INT NOT NULL,
    INDEX (ID_EQUIPO_JUGADOR, ID_EQUIPO, ID_JUGADOR, NUMERO),
    PRIMARY KEY (ID_EQUIPO_JUGADOR)
);

DROP TABLE IF EXISTS JUGADOR;
CREATE TABLE IF NOT EXISTS JUGADOR (
	ID_JUGADOR INT AUTO_INCREMENT,
    NOMBRE VARCHAR(30) NOT NULL,
    APELLIDO VARCHAR(30) NOT NULL,
    NACIONALIDAD VARCHAR(30) NOT NULL,
    INDEX (ID_JUGADOR),
    PRIMARY KEY (ID_JUGADOR)
);

ALTER TABLE EQUIPO 
ADD FOREIGN KEY (ID_CIUDAD) REFERENCES CIUDAD(ID_CIUDAD), 
ADD FOREIGN KEY (ID_ESTADIO) REFERENCES ESTADIO(ID_ESTADIO), 
ADD FOREIGN KEY (ID_ENTRENADOR) REFERENCES ENTRENADOR(ID_ENTRENADOR);

ALTER TABLE PARTIDO
ADD FOREIGN KEY (ID_EQUIPO_1) REFERENCES EQUIPO(ID_EQUIPO), 
ADD FOREIGN KEY (ID_EQUIPO_2) REFERENCES EQUIPO(ID_EQUIPO), 
ADD FOREIGN KEY (ID_ESTADIO) REFERENCES ESTADIO (ID_ESTADIO);

ALTER TABLE ESTADIO
ADD FOREIGN KEY (ID_CIUDAD) REFERENCES CIUDAD(ID_CIUDAD);

ALTER TABLE EQUIPO_JUGADOR
ADD FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPO(ID_EQUIPO), 
ADD FOREIGN KEY (ID_JUGADOR) REFERENCES JUGADOR(ID_JUGADOR);

DROP TABLE IF EXISTS LOG_EQUIPO;
CREATE TABLE IF NOT EXISTS LOG_EQUIPO (
	ID_LOG INT AUTO_INCREMENT,
    ACCION VARCHAR(30) NOT NULL,
    TABLA VARCHAR(30) NOT NULL,
    USUARIO VARCHAR(100) NOT NULL,
    FECHA DATE,
    HORA TIME,
    EQUIPO_NOMBRE VARCHAR(50) NOT NULL,
    ID_EQUIPO INT NOT NULL,
    PRIMARY KEY (ID_LOG)
);

DROP TABLE IF EXISTS LOG_JUGADOR;
CREATE TABLE IF NOT EXISTS LOG_JUGADOR (
	ID_LOG INT AUTO_INCREMENT,
    ACCION VARCHAR(30) NOT NULL,
    TABLA VARCHAR(30) NOT NULL,
    USUARIO VARCHAR(100),
    FECHA DATE,
    HORA TIME,
    OLDVALUE VARCHAR(100),
    NEWVALUE VARCHAR(100),
    PRIMARY KEY (ID_LOG)
);