DROP TRIGGER IF EXISTS TRG_LOG_EQUIPO;
DELIMITER //
CREATE TRIGGER TRG_LOG_EQUIPO AFTER INSERT ON PREMIER_LEAGUE_DB.EQUIPO
FOR EACH ROW
BEGIN

INSERT INTO LOG_EQUIPO(ACCION, TABLA, USUARIO, FECHA, HORA, EQUIPO_NOMBRE, ID_EQUIPO)
VALUES ('INSERT', 'EQUIPO', CURRENT_USER(), DATE(NOW()), TIME(NOW()), NEW.NOMBRE, NEW.ID_EQUIPO);

END//
DELIMITER ;

DROP TRIGGER IF EXISTS TRG_LOG_JUGADOR;
DELIMITER //
CREATE TRIGGER TRG_LOG_JUGADOR BEFORE UPDATE ON PREMIER_LEAGUE_DB.JUGADOR
FOR EACH ROW
BEGIN

INSERT INTO LOG_JUGADOR(ACCION, TABLA, USUARIO, FECHA, HORA, OLDVALUE, NEWVALUE)
VALUES ('UPDATE', 'JUGADOR', CURRENT_USER(), DATE(NOW()), TIME(NOW()), CONCAT(OLD.NOMBRE, ' ', OLD.APELLIDO), CONCAT(NEW.NOMBRE, ' ', NEW.APELLIDO));

END//
DELIMITER ;