DROP VIEW IF EXISTS VW_EQUIPO_CIUDAD;
CREATE VIEW VW_EQUIPO_CIUDAD AS
SELECT E.NOMBRE AS EQUIPO, C.NOMBRE AS CIUDAD
FROM EQUIPO E INNER JOIN CIUDAD C
ON E.ID_CIUDAD = C.ID_CIUDAD;

DROP VIEW IF EXISTS VW_EQUIPO_CANTIDAD_JUGADORES;
CREATE VIEW VW_EQUIPO_CANTIDAD_JUGADORES AS
SELECT E.NOMBRE AS EQUIPO, COUNT(EJ.ID_JUGADOR) AS CANTIDAD_JUGADORES
FROM EQUIPO E
INNER JOIN EQUIPO_JUGADOR EJ ON E.ID_EQUIPO = EJ.ID_EQUIPO
INNER JOIN JUGADOR J ON EJ.ID_JUGADOR = J.ID_JUGADOR
GROUP BY E.NOMBRE;

DROP VIEW IF EXISTS VW_JUGADORES_NACIONALIDAD;
CREATE VIEW VW_JUGADORES_NACIONALIDAD AS
SELECT NACIONALIDAD, COUNT(*) AS CANTIDAD
FROM JUGADOR 
GROUP BY NACIONALIDAD ORDER BY CANTIDAD DESC;

DROP VIEW IF EXISTS VW_DETALLES_PARTIDOS;
CREATE VIEW VW_DETALLES_PARTIDOS AS
SELECT P.FECHA AS FECHA_ENCUENTRO, E1.NOMBRE AS EQUIPO_1 , E2.NOMBRE AS EQUIPO_2, ES.NOMBRE AS ESTADIO
FROM PARTIDO P 
INNER JOIN EQUIPO E1 ON P.ID_EQUIPO_1 = E1.ID_EQUIPO
INNER JOIN EQUIPO E2 ON P.ID_EQUIPO_2 = E2.ID_EQUIPO
INNER JOIN ESTADIO ES ON P.ID_ESTADIO = ES.ID_ESTADIO;

DROP VIEW IF EXISTS VW_ENTRENADORES_EQUIPOS;
CREATE VIEW VW_ENTRENADORES_EQUIPOS AS
SELECT CONCAT(EN.NOMBRE, ' ', EN.APELLIDO) AS ENTRENADOR, E.NOMBRE AS EQUIPO, EN.TITULOS_OBTENIDOS AS TROFEOS_TOTALES
FROM ENTRENADOR EN 
INNER JOIN EQUIPO E ON E.ID_ENTRENADOR = EN.ID_ENTRENADOR
ORDER BY EN.TITULOS_OBTENIDOS DESC;