DROP FUNCTION IF EXISTS FN_JUGADOR_RETORNAR;
DELIMITER //
CREATE FUNCTION FN_JUGADOR_RETORNAR (P_NOMBRE VARCHAR(30))
RETURNS VARCHAR(100)
DETERMINISTIC
BEGIN
DECLARE v_nombre_apellido VARCHAR(100);

SELECT CONCAT(NOMBRE, ' ', APELLIDO) INTO v_nombre_apellido
FROM JUGADOR WHERE NOMBRE LIKE CONCAT('%', P_NOMBRE, '%') OR APELLIDO LIKE CONCAT('%', P_NOMBRE, '%') LIMIT 1;

RETURN v_nombre_apellido;
END //
DELIMITER ;

DROP FUNCTION IF EXISTS FN_ESTADIO_CIUDAD;
DELIMITER //
CREATE FUNCTION FN_ESTADIO_CIUDAD (P_ID_ESTADIO INT)
RETURNS VARCHAR(100)
DETERMINISTIC
BEGIN
DECLARE v_estadio_ciudad VARCHAR(100);

SELECT CONCAT('Estadio: ', E.NOMBRE, ' Ciudad: ', C.NOMBRE) INTO v_estadio_ciudad
FROM ESTADIO E INNER JOIN CIUDAD C 
ON E.ID_CIUDAD = C.ID_CIUDAD
WHERE ID_ESTADIO = P_ID_ESTADIO LIMIT 1;

RETURN v_estadio_ciudad;
END //
DELIMITER ;